# Knowledge based graph -----------------------------------------------------------------------------------------------

kb <- empty.graph(nodes(empty_net))

arc.set <- matrix(c("Majority.COVID.19.variant_t-1", "Reinfections_t",
                    "Majority.COVID.19.variant_t-1", "New.infections_t",
                    "Majority.COVID.19.variant_t-1", "Hospital.admissions_t",
                    "Majority.COVID.19.variant_t-1", "Patients.in.MVBs_t",
                    "Majority.COVID.19.variant_t-1", "COVID.19.deaths.on.certificate_t",
                    "Majority.COVID.19.variant_t-1", "Lockdown.severity_t",
                    "Majority.COVID.19.variant_t-1", "Second.dose.uptake_t",
                    "First.dose.uptake_t-1", "Second.dose.uptake_t",                                    
                    "Second.dose.uptake_t-1", "Third.dose.uptake_t",                                                                 
                    "Reinfections_t-1", "New.cases_t", 
                    "New.infections_t-1", "New.cases_t",
                    "Tests.across.all.4.Pillars_t-1", "New.cases_t",
                    "New.cases_t-1","Hospital.admissions_t",
                    "New.cases_t-1", "Second.dose.uptake_t",
                    "Hospital.admissions_t-1", "Patients.in.hospital_t",
                    "Patients.in.hospital_t-1", "COVID.19.deaths.on.certificate_t",
                    "Patients.in.hospital_t-1","Patients.in.MVBs_t",
                    "Patients.in.hospital_t-1", "Face.masks_t",
                    "Patients.in.hospital_t-1", "Lockdown.severity_t",
                    "Patients.in.MVBs_t-1", "COVID.19.deaths.on.certificate_t",
                    "Patients.in.MVBs_t-1", "Face.masks_t",
                    "Patients.in.MVBs_t-1", "Lockdown.severity_t",
                    "COVID.19.deaths.on.certificate_t-1", "Excess.mortality_t",
                    "COVID.19.deaths.on.certificate_t-1", "Face.masks_t",
                    "COVID.19.deaths.on.certificate_t-1", "Lockdown.severity_t",
                    "Lockdown.severity_t-1", "Excess.mortality_t",
                    "Lockdown.severity_t-1", "Face.masks_t",
                    "Lockdown.severity_t-1", "Flights.7.day.moving.average_t",                                                                                       
                    "Lockdown.severity_t-1", "OpenTable.restaurant.bookings.London.index_t",                                                                         
                    "Lockdown.severity_t-1", "Google.homeworking.Greater.London.mobility.index_t",                                                                   
                    "Lockdown.severity_t-1", "Google.workplace.Greater.London.mobility.index_t",                                                                     
                    "Lockdown.severity_t-1", "Apple.walking.London.mobility.index_t",                                                                                
                    "Lockdown.severity_t-1", "Google.parks.Greater.London.mobility.index_t",                                                                         
                    "Lockdown.severity_t-1", "Google.retail.recreation.Greater.London.mobility.index_t",                                                           
                    "Lockdown.severity_t-1", "Google.grocery.pharmacy.Greater.London.mobility.index_t",                                                            
                    "Lockdown.severity_t-1", "Google.transit.stations.mobility.index_t",                                                                               
                    "Lockdown.severity_t-1", "TfL.Tube.mobility.index_t",                                                                                              
                    "Lockdown.severity_t-1", "TfL.Bus.mobility.index_t",                                                                                               
                    "Lockdown.severity_t-1", "Citymapper.journeys.mobility.index_t",
                    "Lockdown.severity_t-1", "Schools_t",
                    "Season_t-1", "Reinfections_t",
                    "Season_t-1", "New.infections_t",
                    "Season_t-1", "Lockdown.severity_t",
                    "Season_t-1", "Flights.7.day.moving.average_t",                                                                                       
                    "Season_t-1", "OpenTable.restaurant.bookings.London.index_t",                                                                         
                    "Season_t-1", "Google.homeworking.Greater.London.mobility.index_t",                                                                   
                    "Season_t-1", "Google.workplace.Greater.London.mobility.index_t",                                                                     
                    "Season_t-1", "Apple.walking.London.mobility.index_t",                                                                                
                    "Season_t-1", "Google.parks.Greater.London.mobility.index_t",                                                                         
                    "Season_t-1", "Google.retail.recreation.Greater.London.mobility.index_t",                                                           
                    "Season_t-1", "Google.grocery.pharmacy.Greater.London.mobility.index_t",                                                            
                    "Season_t-1", "Google.transit.stations.mobility.index_t",                                                                               
                    "Season_t-1", "TfL.Tube.mobility.index_t",                                                                                              
                    "Season_t-1", "TfL.Bus.mobility.index_t",                                                                                               
                    "Season_t-1", "Citymapper.journeys.mobility.index_t",
                    "Season_t-1", "Schools_t",
                    "OpenTable.restaurant.bookings.London.index_t-1", "Flights.7.day.moving.average_t",
                    "OpenTable.restaurant.bookings.London.index_t-1", "Google.transit.stations.mobility.index_t",
                    "OpenTable.restaurant.bookings.London.index_t-1", "TfL.Tube.mobility.index_t",
                    "OpenTable.restaurant.bookings.London.index_t-1", "TfL.Bus.mobility.index_t",
                    "OpenTable.restaurant.bookings.London.index_t-1", "Citymapper.journeys.mobility.index_t",
                    "Google.homeworking.Greater.London.mobility.index_t-1", "Flights.7.day.moving.average_t",
                    "Google.homeworking.Greater.London.mobility.index_t-1", "Google.transit.stations.mobility.index_t",
                    "Google.homeworking.Greater.London.mobility.index_t-1", "TfL.Tube.mobility.index_t",
                    "Google.homeworking.Greater.London.mobility.index_t-1", "TfL.Bus.mobility.index_t",
                    "Google.homeworking.Greater.London.mobility.index_t-1", "Citymapper.journeys.mobility.index_t",
                    "Google.workplace.Greater.London.mobility.index_t-1", "Flights.7.day.moving.average_t",
                    "Google.workplace.Greater.London.mobility.index_t-1", "Google.transit.stations.mobility.index_t",
                    "Google.workplace.Greater.London.mobility.index_t-1", "TfL.Tube.mobility.index_t",
                    "Google.workplace.Greater.London.mobility.index_t-1", "TfL.Bus.mobility.index_t",
                    "Google.workplace.Greater.London.mobility.index_t-1", "Citymapper.journeys.mobility.index_t",
                    "Apple.walking.London.mobility.index_t-1", "Flights.7.day.moving.average_t",
                    "Apple.walking.London.mobility.index_t-1", "Google.transit.stations.mobility.index_t",
                    "Apple.walking.London.mobility.index_t-1", "TfL.Tube.mobility.index_t",
                    "Apple.walking.London.mobility.index_t-1", "TfL.Bus.mobility.index_t",
                    "Apple.walking.London.mobility.index_t-1", "Citymapper.journeys.mobility.index_t",
                    "Google.parks.Greater.London.mobility.index_t-1",  "Flights.7.day.moving.average_t",
                    "Google.parks.Greater.London.mobility.index_t-1",  "Google.transit.stations.mobility.index_t",
                    "Google.parks.Greater.London.mobility.index_t-1",  "TfL.Tube.mobility.index_t",
                    "Google.parks.Greater.London.mobility.index_t-1",  "TfL.Bus.mobility.index_t",
                    "Google.parks.Greater.London.mobility.index_t-1",  "Citymapper.journeys.mobility.index_t",
                    "Google.retail.recreation.Greater.London.mobility.index_t-1",  "Flights.7.day.moving.average_t",
                    "Google.retail.recreation.Greater.London.mobility.index_t-1",  "Google.transit.stations.mobility.index_t",
                    "Google.retail.recreation.Greater.London.mobility.index_t-1",  "TfL.Tube.mobility.index_t",
                    "Google.retail.recreation.Greater.London.mobility.index_t-1",  "TfL.Bus.mobility.index_t",
                    "Google.retail.recreation.Greater.London.mobility.index_t-1",  "Citymapper.journeys.mobility.index_t",
                    "Google.grocery.pharmacy.Greater.London.mobility.index_t-1",  "Flights.7.day.moving.average_t",
                    "Google.grocery.pharmacy.Greater.London.mobility.index_t-1",  "Google.transit.stations.mobility.index_t",
                    "Google.grocery.pharmacy.Greater.London.mobility.index_t-1",  "TfL.Tube.mobility.index_t",
                    "Google.grocery.pharmacy.Greater.London.mobility.index_t-1",  "TfL.Bus.mobility.index_t",
                    "Google.grocery.pharmacy.Greater.London.mobility.index_t-1",  "Citymapper.journeys.mobility.index_t"
), 
byrow = TRUE, ncol = 2)

arcs(kb) <- arc.set
